#!/bin/sh
getuser(){ \
    if [ "$(uname)" == "Darwin" ];then 
        listname=$(dscl . list /Users | grep -v '_\|root\|daemon') #> $tempuser)
    else
        # HACK: Temporary to get user name
        listname=$(grep "1000\|0:0:" /etc/passwd | cut -d: -f1)
    fi
    tempuser=$(mktemp)

    if [ "$listname | wc -l" != 1 ];then
        echo "There are more than one user. Choose User:"
        while [ -z $name ]; do
            select user in $listname; do
                case $user in
                    *)  name=$user
                        break ;;
                esac
            done
        done
    fi
}
getuser
